Changes to build prototypes to support building on FreeBSD 9.1-RC2 amd64
* Bashism in configure:
./configure: ${ac_cv_search_addstr:2}: Bad substitution

* Configure finds libcurl in /usr/local, but /usr/local/include isn't in CFLAGS:
cgminer.c:39:10: fatal error: 'curl/curl.h' file not found

* Configure misdetects amd64 as 32-bit; fails when trying to link in sse2_64:
cgminer-sha256_sse2_amd64.o: In function `scanhash_sse2_64':
./cgminer/sha256_sse2_amd64.c:98: undefined reference to `sha256_sse2_64_new'
cgminer-sha256_sse4_amd64.o: In function `scanhash_sse4_64':
./cgminer/sha256_sse4_amd64.c:96: undefined reference to `CalcSha256_x64_sse4'
./cgminer/sha256_sse4_amd64.c:97: undefined reference to `CalcSha256_x64_sse4'